use std::{fs, path::Path};

use image::DynamicImage;
use lofty::{file::TaggedFileExt, picture::PictureType};

use crate::util;

/// Size of cached cover arts in pixels
const CACHED_SIZE: u32 = 256;

/// None means track has no embedded art
/// Cache files generated by this are stored in `~/.cache/refrain/covers/<hash>.jpg`
pub fn load_or_extract(track_path: &Path) -> Option<DynamicImage> {
    let file = util::cache_path(track_path, "covers", "jpg");

    // cache hit!
    if let Ok(bytes) = fs::read(&file) {
        if bytes.is_empty() {
            // if the file is empty, it means that track has no cover art, so it's marked and we
            // don't have to parse it using lofty again (it is not a very cheap operation)
            return None;
        }
        if let Ok(image) = image::load_from_memory(&bytes) {
            // image exists in cache, we return it from cache
            return Some(image);
        }
    }

    // cache miss, generate cache file for this cover and resize to 256x256
    // image.thumbnail is faster than resize, but has lower quality, I have not checked how much
    // worse it is, due to speed probably being more important here.
    let cover = extract(track_path).map(|image| image.thumbnail(CACHED_SIZE, CACHED_SIZE));

    // create dir (~/.cache/refrain/covers) if non-existant
    if let Some(parent) = file.parent() {
        let _ = fs::create_dir_all(parent);
    }

    match &cover {
        Some(image) => {
            // cover art has been found, save it to the cache file
            let _ = image
                .to_rgb8()
                .save_with_format(&file, image::ImageFormat::Jpeg);
        },
        None => {
            // no cover art (or couldn't find), save it as a 0 byte file so we don't need to parse
            // it again
            let _ = fs::write(&file, []);
        },
    }

    cover
}

/// Extracts raw image file in full res from the cover art (first available)
fn extract(track_path: &Path) -> Option<DynamicImage> {
    let tagged = lofty::read_from_path(track_path).ok()?;
    let tag = tagged
        .primary_tag()
        .or_else(|| tagged.first_tag())?;

    let picture = tag
        .pictures()
        .iter()
        .find(|p| p.pic_type() == PictureType::CoverFront)
        .or_else(|| tag.pictures().first())?; // if it can't find the CoverFront picture type, it'll
    // take first available

    image::load_from_memory(picture.data()).ok()
}
