use std::{
    fs,
    path::{Path, PathBuf},
};

use image::DynamicImage;
use lofty::{file::TaggedFileExt, picture::PictureType};

use crate::util;

/// Size of cached cover arts in pixels
const CACHED_SIZE: u32 = 256;

/// None means track has no embedded art
/// Cache files generated by this are stored in `~/.cache/refrain/covers/<hash>.jpg`
/// Hash is also stored in `~/.cache/refrain/cover_refs/<hash path+mtime>.txt`, so tracks with same
/// cover art are loaded only once
pub fn load_or_extract(track_path: &Path) -> Option<DynamicImage> {
    let ref_file = util::cache_path(track_path, "cover_refs", "txt");

    // cache hit!
    if let Ok(hash) = fs::read_to_string(&ref_file) {
        if hash.is_empty() {
            // if the file is empty, it means that track has no cover art, so it's marked and we
            // don't have to parse it using lofty again (it is not a very cheap operation)
            return None;
        }
        if let Ok(bytes) = fs::read(cover_file(&hash)) && let Ok(image) = image::load_from_memory(&bytes) {
            // image exists in cache, we return it from cache
            return Some(image);
        }
    }

    // cache miss, read track with lofty
    if let Some(parent) = ref_file.parent() {
        let _ = fs::create_dir_all(parent);
    }

    let Some(data) = extract(track_path) else {
        // no cover art, mark it so we don't need to parse it again
        let _ = fs::write(&ref_file, "");
        return None;
    };

    let hash = format!("{:016x}", util::fnv1a(&data));
    let file = cover_file(&hash);

    let image = if let Ok(bytes) = fs::read(&file) && let Ok(image) = image::load_from_memory(&bytes) {
        // another track with same cover art is already cached, no need to decode it!
        image
    } else {
        let image = image::load_from_memory(&data).ok()?.thumbnail(CACHED_SIZE, CACHED_SIZE);

        if let Some(parent) = file.parent() {
            let _ = fs::create_dir_all(parent);
        }

        let _ = image.to_rgb8().save_with_format(&file, image::ImageFormat::Jpeg);
        image
    };

    let _ = fs::write(&ref_file, &hash);
    Some(image)
}

fn cover_file(hash: &str) -> PathBuf {
    util::cache_dir().join("covers").join(format!("{hash}.jpg"))
}

/// Extracts raw image file in full res from the cover art (first available)
fn extract(track_path: &Path) -> Option<Vec<u8>> {
    let tagged = lofty::read_from_path(track_path).ok()?;
    let tag = tagged
        .primary_tag()
        .or_else(|| tagged.first_tag())?;

    let picture = tag
        .pictures()
        .iter()
        .find(|p| p.pic_type() == PictureType::CoverFront)
        .or_else(|| tag.pictures().first())?; // if it can't find the CoverFront picture type, it'll
    // take first available
    
    Some(picture.data().to_vec())
}

/// Path to cached cover file, creates it on cache miss. None if track has no cover art
pub fn cached_file(track_path: &Path) -> Option<PathBuf> {
    load_or_extract(track_path)?;
    let hash = fs::read_to_string(util::cache_path(track_path, "cover_refs", "txt")).ok()?;
    Some(cover_file(&hash))
}
