use std::{
    fs::{self, File},
    io::{Read, Write},
    path::Path,
};

use audio_waveform::{ChannelMode, Measure, WaveformOptions};

use crate::util;

pub const WAVEFORM_POINTS: usize = 512;
// we use this instead of Vec<u8> as we know exactly how many points we have in each waveform
// For now we keep it as u8 as its probably enough precision, audio-waveform has native u8 functions
// so we dont need to convert from f32 to it
pub type WaveformData = [u8; WAVEFORM_POINTS];

/// Decode file to peaks, or read from disk cache
/// Cache files generated by this are stored in `~/.cache/refrain/waveforms/<hash>.bin`
pub fn load_or_compute(track_path: &Path) -> Option<WaveformData> {
    let file = util::cache_path(track_path, "waveforms", "bin");

    // check for disk cache
    if let Ok(mut f) = File::open(&file) {
        let mut data = [0u8; WAVEFORM_POINTS];
        if f.read_exact(&mut data).is_ok() {
            // hit cache! return that data
            return Some(data);
        }
    }

    // cache miss, generate with audio-waveform
    let options = WaveformOptions::new(WAVEFORM_POINTS)
        .measure(Measure::Peak)
        .channels(ChannelMode::Mix)
        .normalize(true);

    let (points, _duration) = audio_waveform::generate_u8(track_path, &options).ok()?;

    let data: WaveformData = points.try_into().ok()?;

    // ... check if dir (~/.cache/refrain/waveforms) exists, if not create
    if let Some(parent) = file.parent() {
        let _ = fs::create_dir_all(parent);
    }
    // and then create file
    if let Ok(mut f) = File::create(&file) {
        let _ = f.write_all(&data);
    }

    Some(data)
}
